version: '3.8'
services:
  app:
    container_name: messaging_backend
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/urs/src/app
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: messaging_backend_postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: messaging_backend_pgadmin
    env_file:
      - .env
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge
